openapi: 3.0.3
info:
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8083
tags:
  - name: registration
    description: Registration Service
paths:
  /registration/:
    post:
      tags:
        - Registration
      summary: Đăng ký lịch học
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDTO'           
      responses:
        201:
          description: Thành công
          content:
            application/json:
              schema:
                type: string
        400:
          description: Thất bại
          content:
            application/json:
              schema:
                type: string
  
  /registration/{id}:
    put:
      tags:
        - Registration
      summary: Cập nhật đơn đăng ký
      operationId: update
      parameters:
        - name: id
          description: ID đơn đăng ký
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDTO'
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                type: string
        400:
          description: Thất bại
          content:
            application/json:
              schema:
                type: string
  
  /registration/{studentCode}:
    get:
      tags:
        - Registration
      summary: Lấy thông tin đơn đăng ký lớp học
      operationId: getDetail
      description: Lấy thông tin đơn đăng ký lớp học phần của sinh viên
      parameters:
        - name: studentCode
          description: Mã sinh viên
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        404:
          description: Không tìm thấy thông tin đơn đăng ký của sinh viên
          content:
            application/json:
              schema:
                type: string
components:
  schemas: 
    RegistrationDetail:
      type: object
      properties:
        subjectClassCode:
          type: string
          description: Mã lớp học

    Registration:
      type: object
      properties:
        id:
          type: integer
          format: int32
        studentCode:
          type: string
          description: Mã sinh viên
        created_at:
          type: string
          format: date
        note:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/RegistrationDetail'  
    RegistrationDTO:
      type: object
      properties:
        studentCode:
          type: string
          description: Mã sinh viên
        note:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/RegistrationDetail'  