openapi: 3.0.3
info:
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8085
tags:
  - name: notification
    description: Notification Service
paths:   
   /notification/:
    post:
      tags:
        - notification
      summary: Gửi mail
      operationId: send
      description: Gửi mail đến địa chỉ email xác định
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailMessage'       
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                type: string
        400:
          description: Thất bại
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    EmailMessage:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email đích
        title:
          type: string
          description: Tiêu đề của mail
        text:
          type: string
          description: Nội dung mail