openapi: 3.0.3
info:
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8082
tags:
  - name: subject_class
    description: SubjectClass Service
paths:
  /subject-class/all/:
    get:
      tags:
        - subject_class
      summary: Lấy thông tin tất cả lớp học phần
      operationId: getAll
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubjectClass'  
  /subject-class/{id}:
    get:
      tags:
        - subject_class
      summary: Lấy thông tin lớp học phần
      operationId: getDetail
      parameters:
        - name: id
          description: Mã lớp học
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectClass'                    
        404:
          description: Không tìm thấy lớp học phần
          content:
            application/json:
              schema:
                type: string
              
  /subject-class/{id}/schedule/:
    get:
      tags:
        - Subject Class
      summary: Lấy thông tin lịch học của lớp học phần
      operationId: getSchedule
      parameters:
        - name: id
          description: Mã lớp học
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
        404:
          description: Không tìm thấy lớp học phần
          content:
            application/json:
              schema:
                type: string

  /subject-class/{id}/number/{action}/:  
    put:
      tags:
        - Subject Class
      summary: Cập nhật sĩ số cho lớp học phần
      operationId: updateNumber
      description: Thực hiện tăng sĩ số lớp học lên 1 nhưng không vượt quá sĩ số tối đa.
      parameters:
        - name: id
          description: Mã lớp học
          required: true
          in: path
          schema:
            type: string 
        - name: action
          description: Hành động cập nhật sĩ số
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: Thành công
          content:
            application/json:
              schema:
                type: string
        400:
          description: Thất bại
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Schedule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        weeks:
          type: array
          items:
            type: integer
            format: int32
          description: Danh sách tuần học
        sessionStart:
          type: integer
          format: int32
          description: Kíp bắt đầu
        sessionEnd:
          type: integer
          format: int32
          description: Kíp kết thúc
        dayOfWeek:
          type: string
          description: Học ngày thứ mấy
        des:
          type: string
    SubjectClass:
      type: object
      properties:
        code:
          type: string
        maxNumber:
          type: integer
          format: int32
          description: Sĩ số tối đa
        number:
          type: integer
          format: int32
          description: Sĩ số hiện tại
        isActive:
          type: boolean
        des:
          type: string
        subjectCode:
          type: string
          description: Mã môn học
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'