openapi: 3.0.3
info:
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8084
tags:
  - name: student register subject
    description: Student Register Subject Service
paths:
   /task/:
     post:
       tags:
         - student register subject
       summary: Start
       operationId: start
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/StudentRegistration'
       responses:
         200:
           description: Thành công
           content:
             application/json:
              schema:
               type: string
               description: message trả về kết quả
         400:
           description: Thất bại
           content:
             application/json:
               schema:
                 type: string
    
   /task/{id}:
     get:
       tags:
         - student register subject
       summary: Lấy thông tin quá trình xử lý
       operationId: getDetail
       parameters:
         - name: id
           description: Mã tiến trình (Mã sinh viên)
           in: path
           required: true
           schema:
             type: string
       responses:
         200:
           description: Thành công
           content:
             text/event-stream:
               schema:
                 type: array
                 items:
                   $ref: '#/components/schemas/Process'
         404:
           description: Không tìm thấy tiến trình
     delete:
       tags:
         - student register subject
       summary: Xóa tiến trình
       operationId: delete
       parameters:
         - name: id
           description: Mã tiến trình(Mã sinh viên)
           in: path
           required: true
           schema:
             type: string
       responses:
         204:
           description: Thành công
         404:
           description: Không tìm thấy tiến trình
        
components:
  schemas:
    StudentRegistration:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID đơn đăng ký
        studentCode:
          type: string
          description: Mã sinh viên
        details:
          type: array
          items:
            $ref: '#/components/schemas/StudentRegistrationDetail'
    StudentRegistrationDetail:
      type: object
      properties:
        subjectCode:
          type: string
          description: Mã môn học
        subjectClassCode:
          type: string
          description: Mã lớp học
    Process:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID của giai đoạn
        name:
          type: string
          description: Tên giai đoạn
        status:
          type: boolean
          description: Trạng thái giai đoạn